### ISSUE TITLE
[Idea] Use this project to make this web app to be more better

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [Vencord/Android#11]
[https://github.com/tsukasa/BdBrowser](https://github.com/tsukasa/BdBrowser)

So, if you can to modify that chrome extension to get more mobile-friendly UI (similar to react-native app), some improvements in performace to get on that web version of the Discord app via this extension and scripts and your app to be based on chromium with extension support by kiwi browser chrome extension support project, you can make the best modded Discord client for Android that can replace every modded Discord client for Android in the whole history and the future.

Just tell me, what you think about that extension and idea to add it as planned, not non-planned.

**Comment by Vendicated** [comment]
what? That extension is just BD for web, how does that in any way relate to the mobile app

**Comment by Vendicated** [comment]
we're not interested in that in the slightest. Vencord is a different mod not affiliated with betterdiscord. If someone else wants to do this then cool but that's very out of scope for this project
