### ISSUE TITLE
WHERE PLUGINS???

### ISSUE THREAD

**Issue by idontveapc** [Vencord/Android#13]
>:( you forgot!?

**Comment by Vendicated** [comment]
what?

**Comment by idontveapc** [comment]
where are plugins that vencord for windows/linux/macos have??

**Comment by idontveapc** [comment]
where are the plugins that vencord for windows/linux/macos versions have??

**Comment by Vendicated** [comment]
In the settings...

**Comment by idontveapc** [comment]
oops, i went vendetta discord server for plugins (◠ 𓎟 ◠!)
