### ISSUE TITLE
Can't join VC

### ISSUE THREAD

**Issue by Corbony** [Vencord/Android#18]
I am wondering if this is a bug because I can't join a VC to chat so I have to join on a different discord client. Any help?

**Comment by ILuvDespair** [comment]
Do you have this enabled?

![Vencord_Desktop_FFEXhoxALs](https://github.com/Vencord/Android/assets/131752112/1997d3ed-e7ac-42ac-8433-d8ea796b8a2d)

**Comment by Vendicated** [comment]
not a thing on the mobile website. use the normal discord app
