### ISSUE TITLE
Can't open Vencord settings.

### ISSUE THREAD

**Issue by KVKMYH72VT** [Vencord/Android#7]
I'm in settings but the settings labeled Vencord doesn't open.

https://user-images.githubusercontent.com/128162906/226412557-15fc43f0-54ba-4284-ade5-5902d4ee5f05.mp4

**Comment by Vendicated** [comment]
known issue, needs to be fixed upstream

**Comment by KVKMYH72VT** [comment]
Okay

**Comment by KVKMYH72VT** [comment]
Thanks. Also I'm new.

**Comment by KVKMYH72VT** [comment]
First bug. I installed today

**Comment by Voidxx99back** [comment]
do you know when it may be fixed?

**Comment by KVKMYH72VT** [comment]
Idk

**Comment by MeguminSama** [comment]
Be patient. we will get to it.

**Comment by craftpro100** [comment]
When will it be fixed?

**Comment by KVKMYH72VT** [comment]
> Be patient. we will get to it.

**Comment by KVKMYH72VT** [comment]
> When will it be fixed?

https://github.com/Vencord/Android/issues/7#issuecomment-1477752067

**Comment by Vendicated** [comment]
(already fixed)
